[phases.setup]
nixPkgs = ["libreoffice", "poppler_utils", "fontconfig", "liberation_ttf"]

[phases.install]
cmds = ["python -m venv /opt/venv && /opt/venv/bin/pip install -r requirements.txt"]

[start]
cmd = "/opt/venv/bin/python app.py"
